import { ApplianceItem } from '../types';

export const DEFAULT_APPLIANCES: ApplianceItem[] = [
  {
    id: 'aircon_1_5hp_inverter',
    nameTl: '1.5 HP Inverter Aircon (Silid / Sala)',
    nameEn: '1.5 HP Inverter Aircon (Bedroom/Living)',
    category: 'cooling',
    wattage: 950,
    hoursPerDay: 8,
    quantity: 1,
    iconName: 'wind',
  },
  {
    id: 'aircon_1hp_inverter',
    nameTl: '1.0 HP Inverter Aircon',
    nameEn: '1.0 HP Inverter Aircon',
    category: 'cooling',
    wattage: 700,
    hoursPerDay: 8,
    quantity: 1,
    iconName: 'wind',
  },
  {
    id: 'refrigerator_inverter',
    nameTl: 'Inverter Refrigerator (2-Door / Frost Free)',
    nameEn: 'Inverter Refrigerator (2-Door)',
    category: 'kitchen',
    wattage: 140,
    hoursPerDay: 24, // cycle ~ 50% duty
    quantity: 1,
    iconName: 'refrigerator',
  },
  {
    id: 'electric_fan',
    nameTl: 'Stand / Desk Electric Fan',
    nameEn: 'Stand / Desk Electric Fan',
    category: 'cooling',
    wattage: 65,
    hoursPerDay: 12,
    quantity: 3,
    iconName: 'fan',
  },
  {
    id: 'led_lights',
    nameTl: 'LED Bulbs & Lights (Kabuuang Bahay)',
    nameEn: 'LED Lights (Whole House)',
    category: 'lighting',
    wattage: 12,
    hoursPerDay: 6,
    quantity: 10,
    iconName: 'lightbulb',
  },
  {
    id: 'smart_tv_55',
    nameTl: '55" Smart TV / Soundbar',
    nameEn: '55" Smart TV & Soundbar',
    category: 'entertainment',
    wattage: 110,
    hoursPerDay: 5,
    quantity: 1,
    iconName: 'tv',
  },
  {
    id: 'desktop_computer',
    nameTl: 'Desktop PC / Work From Home Setup',
    nameEn: 'Desktop PC / WFH Setup',
    category: 'entertainment',
    wattage: 220,
    hoursPerDay: 8,
    quantity: 1,
    iconName: 'monitor',
  },
  {
    id: 'induction_cooker',
    nameTl: 'Induction Cooker (Lutuan)',
    nameEn: 'Induction Cooker',
    category: 'kitchen',
    wattage: 1500,
    hoursPerDay: 1.5,
    quantity: 1,
    iconName: 'flame',
  },
  {
    id: 'water_heater_shower',
    nameTl: 'Single Point Shower Water Heater',
    nameEn: 'Electric Shower Water Heater',
    category: 'other',
    wattage: 3500,
    hoursPerDay: 0.5,
    quantity: 1,
    iconName: 'droplets',
  },
  {
    id: 'washing_machine_dryer',
    nameTl: 'Automatic Washing Machine',
    nameEn: 'Automatic Washing Machine',
    category: 'other',
    wattage: 450,
    hoursPerDay: 1,
    quantity: 1,
    iconName: 'shirt',
  },
  {
    id: 'water_pump',
    nameTl: 'Deep Well / Booster Water Pump (0.5 HP)',
    nameEn: 'Water Booster Pump (0.5 HP)',
    category: 'other',
    wattage: 400,
    hoursPerDay: 1,
    quantity: 1,
    iconName: 'gauge',
  },
];
