import { PhilippineRegion } from '../types';

export const PHILIPPINE_REGIONS: PhilippineRegion[] = [
  {
    id: 'ncr',
    name: 'Metro Manila (NCR) / Bulacan / Rizal',
    islandGroup: 'Luzon',
    psh: 4.5,
    description: 'Average 4.5 hrs/day Peak Sun Hours. Standard residential benchmark.',
  },
  {
    id: 'calabarzon',
    name: 'Cavite / Laguna / Batangas / Quezon',
    islandGroup: 'Luzon',
    psh: 4.5,
    description: 'Average 4.5 hrs/day. Magandang sikat ng araw sa kapatagan at baybayin.',
  },
  {
    id: 'central_luzon',
    name: 'Pampanga / Tarlac / Nueva Ecija / Zambales',
    islandGroup: 'Luzon',
    psh: 4.7,
    description: 'Average 4.7 hrs/day. Mainit at malawak na sikat ng araw.',
  },
  {
    id: 'ilocos_cagayan',
    name: 'Ilocos / La Union / Pangasinan / Isabela',
    islandGroup: 'Luzon',
    psh: 4.8,
    description: 'Average 4.8 hrs/day. Mataas na solar radiation lalo na sa Hilagang Luzon.',
  },
  {
    id: 'car_baguio',
    name: 'Cordillera (Baguio / Benguet / Mountain Province)',
    islandGroup: 'Luzon',
    psh: 4.0,
    description: 'Average 4.0 hrs/day. Madalas ang hamog at ulap sa kabundukan.',
  },
  {
    id: 'bicol',
    name: 'Bicol Region (CamSur, Albay, Sorsogon)',
    islandGroup: 'Luzon',
    psh: 4.4,
    description: 'Average 4.4 hrs/day. Karaniwang sikat ng araw na may pana-panahong ulan.',
  },
  {
    id: 'palawan',
    name: 'Palawan & Island Provinces',
    islandGroup: 'Luzon',
    psh: 4.8,
    description: 'Average 4.8 hrs/day. Napakaganda para sa On-Grid at Hybrid systems.',
  },
  {
    id: 'central_visayas',
    name: 'Cebu / Bohol / Negros Oriental / Siquijor',
    islandGroup: 'Visayas',
    psh: 4.7,
    description: 'Average 4.7 hrs/day. Matatag na sikat ng araw sa buong taon.',
  },
  {
    id: 'western_visayas',
    name: 'Iloilo / Bacolod / Aklan / Capiz / Antique',
    islandGroup: 'Visayas',
    psh: 4.6,
    description: 'Average 4.6 hrs/day. Magandang produksyon ng solar.',
  },
  {
    id: 'eastern_visayas',
    name: 'Leyte / Samar / Biliran',
    islandGroup: 'Visayas',
    psh: 4.3,
    description: 'Average 4.3 hrs/day. Mas madalas ang pag-ulan kumpara sa Western Visayas.',
  },
  {
    id: 'davao_region',
    name: 'Davao City & Davao Region',
    islandGroup: 'Mindanao',
    psh: 5.0,
    description: 'Average 5.0 hrs/day. Walang gaanong bagyo at mataas ang araw sa Mindanao.',
  },
  {
    id: 'northern_mindanao',
    name: 'Cagayan de Oro / Bukidnon / Misamis',
    islandGroup: 'Mindanao',
    psh: 4.9,
    description: 'Average 4.9 hrs/day. Magandang solar generation.',
  },
  {
    id: 'soccsksargen_zamboanga',
    name: 'GenSan / South Cotabato / Zamboanga',
    islandGroup: 'Mindanao',
    psh: 5.2,
    description: 'Average 5.2 hrs/day. Isa sa may pinakamataas na solar radiance sa bansa.',
  },
];
